#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# 	listen on port 80
#	returns a page containing "Hello World!" when queried
#	at the root with curl GET request


# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Creating a sample page
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Creating server block files
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
}
" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
