#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# 	listen on port 80
#	returns a page containing "Hello World!" when queried
#	at the root with curl GET request


# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Creating a sample page
echo "Hello World!" > /etc/nginx/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
