#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# 	listen on port 80
#	returns a page containing "Hello World!" when queried
#	at the root with curl GET request


# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
echo "Hello World!" > /etc/nginx/html/index.html

# code for error page and redirect error 404
echo -e "Ceci n'est pas une page" > /etc/nginx/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
