#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Using roundrobin algorithm


# Install HAProxy
sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend http_front
		bind *:80
		default_backend http_back

backend http_back
		balance roundrobin
		server 132031-web-01 34.207.121.58:80 check
		server 132031-web-02 54.237.103.145:80 check
" >> /etc/haproxy/haproxy.cfg

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Start HAProxy
sudo service haproxy restart
