#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely,
# sleep 2 in between
# displays 'I am invincible!!!' when receiving SIGTERM signal


while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
