#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" for the 9th iteration


while [[ $i -le 10 ]]
do
	if [[ $i -ne 9 ]]
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	((i++))
done
